import { IsArray, IsMongoId } from 'class-validator';
import { QuizAnswerDataType } from '../schemas/quiz-answer.schema';

export class CreateQuizAnswerDto {
  @IsMongoId()
  questionId: string;

  //TODO: make validation for answers.
  // Need be at least 2, with at least one correct
  // Id can be generated by service
  @IsArray()
  answers: QuizAnswerDataType[];
}
